// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ups.proto

#ifndef PROTOBUF_ups_2eproto__INCLUDED
#define PROTOBUF_ups_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class UCommands;
class UCommandsDefaultTypeInternal;
extern UCommandsDefaultTypeInternal _UCommands_default_instance_;
class UConnect;
class UConnectDefaultTypeInternal;
extern UConnectDefaultTypeInternal _UConnect_default_instance_;
class UConnected;
class UConnectedDefaultTypeInternal;
extern UConnectedDefaultTypeInternal _UConnected_default_instance_;
class UDeliveryLocation;
class UDeliveryLocationDefaultTypeInternal;
extern UDeliveryLocationDefaultTypeInternal _UDeliveryLocation_default_instance_;
class UDeliveryMade;
class UDeliveryMadeDefaultTypeInternal;
extern UDeliveryMadeDefaultTypeInternal _UDeliveryMade_default_instance_;
class UFinished;
class UFinishedDefaultTypeInternal;
extern UFinishedDefaultTypeInternal _UFinished_default_instance_;
class UGoDeliver;
class UGoDeliverDefaultTypeInternal;
extern UGoDeliverDefaultTypeInternal _UGoDeliver_default_instance_;
class UGoPickup;
class UGoPickupDefaultTypeInternal;
extern UGoPickupDefaultTypeInternal _UGoPickup_default_instance_;
class UResponses;
class UResponsesDefaultTypeInternal;
extern UResponsesDefaultTypeInternal _UResponses_default_instance_;

namespace protobuf_ups_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ups_2eproto

// ===================================================================

class UConnect : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UConnect) */ {
 public:
  UConnect();
  virtual ~UConnect();

  UConnect(const UConnect& from);

  inline UConnect& operator=(const UConnect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UConnect& default_instance();

  static inline const UConnect* internal_default_instance() {
    return reinterpret_cast<const UConnect*>(
               &_UConnect_default_instance_);
  }

  void Swap(UConnect* other);

  // implements Message ----------------------------------------------

  inline UConnect* New() const PROTOBUF_FINAL { return New(NULL); }

  UConnect* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UConnect& from);
  void MergeFrom(const UConnect& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UConnect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 reconnectid = 1;
  bool has_reconnectid() const;
  void clear_reconnectid();
  static const int kReconnectidFieldNumber = 1;
  ::google::protobuf::int64 reconnectid() const;
  void set_reconnectid(::google::protobuf::int64 value);

  // optional int32 numtrucksinit = 2;
  bool has_numtrucksinit() const;
  void clear_numtrucksinit();
  static const int kNumtrucksinitFieldNumber = 2;
  ::google::protobuf::int32 numtrucksinit() const;
  void set_numtrucksinit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UConnect)
 private:
  void set_has_reconnectid();
  void clear_has_reconnectid();
  void set_has_numtrucksinit();
  void clear_has_numtrucksinit();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 reconnectid_;
  ::google::protobuf::int32 numtrucksinit_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UConnected : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UConnected) */ {
 public:
  UConnected();
  virtual ~UConnected();

  UConnected(const UConnected& from);

  inline UConnected& operator=(const UConnected& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UConnected& default_instance();

  static inline const UConnected* internal_default_instance() {
    return reinterpret_cast<const UConnected*>(
               &_UConnected_default_instance_);
  }

  void Swap(UConnected* other);

  // implements Message ----------------------------------------------

  inline UConnected* New() const PROTOBUF_FINAL { return New(NULL); }

  UConnected* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UConnected& from);
  void MergeFrom(const UConnected& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UConnected* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string error = 2;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // required int64 worldid = 1;
  bool has_worldid() const;
  void clear_worldid();
  static const int kWorldidFieldNumber = 1;
  ::google::protobuf::int64 worldid() const;
  void set_worldid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UConnected)
 private:
  void set_has_worldid();
  void clear_has_worldid();
  void set_has_error();
  void clear_has_error();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  ::google::protobuf::int64 worldid_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UGoPickup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UGoPickup) */ {
 public:
  UGoPickup();
  virtual ~UGoPickup();

  UGoPickup(const UGoPickup& from);

  inline UGoPickup& operator=(const UGoPickup& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UGoPickup& default_instance();

  static inline const UGoPickup* internal_default_instance() {
    return reinterpret_cast<const UGoPickup*>(
               &_UGoPickup_default_instance_);
  }

  void Swap(UGoPickup* other);

  // implements Message ----------------------------------------------

  inline UGoPickup* New() const PROTOBUF_FINAL { return New(NULL); }

  UGoPickup* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UGoPickup& from);
  void MergeFrom(const UGoPickup& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UGoPickup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 whid = 2;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 2;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UGoPickup)
 private:
  void set_has_truckid();
  void clear_has_truckid();
  void set_has_whid();
  void clear_has_whid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 whid_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UFinished : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UFinished) */ {
 public:
  UFinished();
  virtual ~UFinished();

  UFinished(const UFinished& from);

  inline UFinished& operator=(const UFinished& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UFinished& default_instance();

  static inline const UFinished* internal_default_instance() {
    return reinterpret_cast<const UFinished*>(
               &_UFinished_default_instance_);
  }

  void Swap(UFinished* other);

  // implements Message ----------------------------------------------

  inline UFinished* New() const PROTOBUF_FINAL { return New(NULL); }

  UFinished* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UFinished& from);
  void MergeFrom(const UFinished& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UFinished* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UFinished)
 private:
  void set_has_truckid();
  void clear_has_truckid();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UDeliveryMade : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UDeliveryMade) */ {
 public:
  UDeliveryMade();
  virtual ~UDeliveryMade();

  UDeliveryMade(const UDeliveryMade& from);

  inline UDeliveryMade& operator=(const UDeliveryMade& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UDeliveryMade& default_instance();

  static inline const UDeliveryMade* internal_default_instance() {
    return reinterpret_cast<const UDeliveryMade*>(
               &_UDeliveryMade_default_instance_);
  }

  void Swap(UDeliveryMade* other);

  // implements Message ----------------------------------------------

  inline UDeliveryMade* New() const PROTOBUF_FINAL { return New(NULL); }

  UDeliveryMade* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UDeliveryMade& from);
  void MergeFrom(const UDeliveryMade& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UDeliveryMade* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 2;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 2;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UDeliveryMade)
 private:
  void set_has_truckid();
  void clear_has_truckid();
  void set_has_packageid();
  void clear_has_packageid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int32 truckid_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UDeliveryLocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UDeliveryLocation) */ {
 public:
  UDeliveryLocation();
  virtual ~UDeliveryLocation();

  UDeliveryLocation(const UDeliveryLocation& from);

  inline UDeliveryLocation& operator=(const UDeliveryLocation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UDeliveryLocation& default_instance();

  static inline const UDeliveryLocation* internal_default_instance() {
    return reinterpret_cast<const UDeliveryLocation*>(
               &_UDeliveryLocation_default_instance_);
  }

  void Swap(UDeliveryLocation* other);

  // implements Message ----------------------------------------------

  inline UDeliveryLocation* New() const PROTOBUF_FINAL { return New(NULL); }

  UDeliveryLocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UDeliveryLocation& from);
  void MergeFrom(const UDeliveryLocation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UDeliveryLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 1;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UDeliveryLocation)
 private:
  void set_has_packageid();
  void clear_has_packageid();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UGoDeliver : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UGoDeliver) */ {
 public:
  UGoDeliver();
  virtual ~UGoDeliver();

  UGoDeliver(const UGoDeliver& from);

  inline UGoDeliver& operator=(const UGoDeliver& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UGoDeliver& default_instance();

  static inline const UGoDeliver* internal_default_instance() {
    return reinterpret_cast<const UGoDeliver*>(
               &_UGoDeliver_default_instance_);
  }

  void Swap(UGoDeliver* other);

  // implements Message ----------------------------------------------

  inline UGoDeliver* New() const PROTOBUF_FINAL { return New(NULL); }

  UGoDeliver* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UGoDeliver& from);
  void MergeFrom(const UGoDeliver& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UGoDeliver* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UDeliveryLocation packages = 2;
  int packages_size() const;
  void clear_packages();
  static const int kPackagesFieldNumber = 2;
  const ::UDeliveryLocation& packages(int index) const;
  ::UDeliveryLocation* mutable_packages(int index);
  ::UDeliveryLocation* add_packages();
  ::google::protobuf::RepeatedPtrField< ::UDeliveryLocation >*
      mutable_packages();
  const ::google::protobuf::RepeatedPtrField< ::UDeliveryLocation >&
      packages() const;

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UGoDeliver)
 private:
  void set_has_truckid();
  void clear_has_truckid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UDeliveryLocation > packages_;
  ::google::protobuf::int32 truckid_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UCommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UCommands) */ {
 public:
  UCommands();
  virtual ~UCommands();

  UCommands(const UCommands& from);

  inline UCommands& operator=(const UCommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UCommands& default_instance();

  static inline const UCommands* internal_default_instance() {
    return reinterpret_cast<const UCommands*>(
               &_UCommands_default_instance_);
  }

  void Swap(UCommands* other);

  // implements Message ----------------------------------------------

  inline UCommands* New() const PROTOBUF_FINAL { return New(NULL); }

  UCommands* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UCommands& from);
  void MergeFrom(const UCommands& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UGoDeliver deliveries = 1;
  int deliveries_size() const;
  void clear_deliveries();
  static const int kDeliveriesFieldNumber = 1;
  const ::UGoDeliver& deliveries(int index) const;
  ::UGoDeliver* mutable_deliveries(int index);
  ::UGoDeliver* add_deliveries();
  ::google::protobuf::RepeatedPtrField< ::UGoDeliver >*
      mutable_deliveries();
  const ::google::protobuf::RepeatedPtrField< ::UGoDeliver >&
      deliveries() const;

  // repeated .UGoPickup pickups = 2;
  int pickups_size() const;
  void clear_pickups();
  static const int kPickupsFieldNumber = 2;
  const ::UGoPickup& pickups(int index) const;
  ::UGoPickup* mutable_pickups(int index);
  ::UGoPickup* add_pickups();
  ::google::protobuf::RepeatedPtrField< ::UGoPickup >*
      mutable_pickups();
  const ::google::protobuf::RepeatedPtrField< ::UGoPickup >&
      pickups() const;

  // optional uint32 simspeed = 3;
  bool has_simspeed() const;
  void clear_simspeed();
  static const int kSimspeedFieldNumber = 3;
  ::google::protobuf::uint32 simspeed() const;
  void set_simspeed(::google::protobuf::uint32 value);

  // optional bool disconnect = 4;
  bool has_disconnect() const;
  void clear_disconnect();
  static const int kDisconnectFieldNumber = 4;
  bool disconnect() const;
  void set_disconnect(bool value);

  // @@protoc_insertion_point(class_scope:UCommands)
 private:
  void set_has_simspeed();
  void clear_has_simspeed();
  void set_has_disconnect();
  void clear_has_disconnect();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UGoDeliver > deliveries_;
  ::google::protobuf::RepeatedPtrField< ::UGoPickup > pickups_;
  ::google::protobuf::uint32 simspeed_;
  bool disconnect_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UResponses : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UResponses) */ {
 public:
  UResponses();
  virtual ~UResponses();

  UResponses(const UResponses& from);

  inline UResponses& operator=(const UResponses& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UResponses& default_instance();

  static inline const UResponses* internal_default_instance() {
    return reinterpret_cast<const UResponses*>(
               &_UResponses_default_instance_);
  }

  void Swap(UResponses* other);

  // implements Message ----------------------------------------------

  inline UResponses* New() const PROTOBUF_FINAL { return New(NULL); }

  UResponses* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UResponses& from);
  void MergeFrom(const UResponses& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UResponses* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UFinished completions = 1;
  int completions_size() const;
  void clear_completions();
  static const int kCompletionsFieldNumber = 1;
  const ::UFinished& completions(int index) const;
  ::UFinished* mutable_completions(int index);
  ::UFinished* add_completions();
  ::google::protobuf::RepeatedPtrField< ::UFinished >*
      mutable_completions();
  const ::google::protobuf::RepeatedPtrField< ::UFinished >&
      completions() const;

  // repeated .UDeliveryMade delivered = 2;
  int delivered_size() const;
  void clear_delivered();
  static const int kDeliveredFieldNumber = 2;
  const ::UDeliveryMade& delivered(int index) const;
  ::UDeliveryMade* mutable_delivered(int index);
  ::UDeliveryMade* add_delivered();
  ::google::protobuf::RepeatedPtrField< ::UDeliveryMade >*
      mutable_delivered();
  const ::google::protobuf::RepeatedPtrField< ::UDeliveryMade >&
      delivered() const;

  // optional string error = 3;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // optional bool finished = 4;
  bool has_finished() const;
  void clear_finished();
  static const int kFinishedFieldNumber = 4;
  bool finished() const;
  void set_finished(bool value);

  // @@protoc_insertion_point(class_scope:UResponses)
 private:
  void set_has_error();
  void clear_has_error();
  void set_has_finished();
  void clear_has_finished();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UFinished > completions_;
  ::google::protobuf::RepeatedPtrField< ::UDeliveryMade > delivered_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  bool finished_;
  friend struct protobuf_ups_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UConnect

// optional int64 reconnectid = 1;
inline bool UConnect::has_reconnectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UConnect::set_has_reconnectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UConnect::clear_has_reconnectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UConnect::clear_reconnectid() {
  reconnectid_ = GOOGLE_LONGLONG(0);
  clear_has_reconnectid();
}
inline ::google::protobuf::int64 UConnect::reconnectid() const {
  // @@protoc_insertion_point(field_get:UConnect.reconnectid)
  return reconnectid_;
}
inline void UConnect::set_reconnectid(::google::protobuf::int64 value) {
  set_has_reconnectid();
  reconnectid_ = value;
  // @@protoc_insertion_point(field_set:UConnect.reconnectid)
}

// optional int32 numtrucksinit = 2;
inline bool UConnect::has_numtrucksinit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UConnect::set_has_numtrucksinit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UConnect::clear_has_numtrucksinit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UConnect::clear_numtrucksinit() {
  numtrucksinit_ = 0;
  clear_has_numtrucksinit();
}
inline ::google::protobuf::int32 UConnect::numtrucksinit() const {
  // @@protoc_insertion_point(field_get:UConnect.numtrucksinit)
  return numtrucksinit_;
}
inline void UConnect::set_numtrucksinit(::google::protobuf::int32 value) {
  set_has_numtrucksinit();
  numtrucksinit_ = value;
  // @@protoc_insertion_point(field_set:UConnect.numtrucksinit)
}

// -------------------------------------------------------------------

// UConnected

// required int64 worldid = 1;
inline bool UConnected::has_worldid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UConnected::set_has_worldid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UConnected::clear_has_worldid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UConnected::clear_worldid() {
  worldid_ = GOOGLE_LONGLONG(0);
  clear_has_worldid();
}
inline ::google::protobuf::int64 UConnected::worldid() const {
  // @@protoc_insertion_point(field_get:UConnected.worldid)
  return worldid_;
}
inline void UConnected::set_worldid(::google::protobuf::int64 value) {
  set_has_worldid();
  worldid_ = value;
  // @@protoc_insertion_point(field_set:UConnected.worldid)
}

// optional string error = 2;
inline bool UConnected::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UConnected::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UConnected::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UConnected::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& UConnected::error() const {
  // @@protoc_insertion_point(field_get:UConnected.error)
  return error_.GetNoArena();
}
inline void UConnected::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UConnected.error)
}
#if LANG_CXX11
inline void UConnected::set_error(::std::string&& value) {
  set_has_error();
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UConnected.error)
}
#endif
inline void UConnected::set_error(const char* value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UConnected.error)
}
inline void UConnected::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UConnected.error)
}
inline ::std::string* UConnected::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:UConnected.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UConnected::release_error() {
  // @@protoc_insertion_point(field_release:UConnected.error)
  clear_has_error();
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UConnected::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:UConnected.error)
}

// -------------------------------------------------------------------

// UGoPickup

// required int32 truckid = 1;
inline bool UGoPickup::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UGoPickup::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UGoPickup::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UGoPickup::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UGoPickup::truckid() const {
  // @@protoc_insertion_point(field_get:UGoPickup.truckid)
  return truckid_;
}
inline void UGoPickup::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UGoPickup.truckid)
}

// required int32 whid = 2;
inline bool UGoPickup::has_whid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UGoPickup::set_has_whid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UGoPickup::clear_has_whid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UGoPickup::clear_whid() {
  whid_ = 0;
  clear_has_whid();
}
inline ::google::protobuf::int32 UGoPickup::whid() const {
  // @@protoc_insertion_point(field_get:UGoPickup.whid)
  return whid_;
}
inline void UGoPickup::set_whid(::google::protobuf::int32 value) {
  set_has_whid();
  whid_ = value;
  // @@protoc_insertion_point(field_set:UGoPickup.whid)
}

// -------------------------------------------------------------------

// UFinished

// required int32 truckid = 1;
inline bool UFinished::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UFinished::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UFinished::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UFinished::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UFinished::truckid() const {
  // @@protoc_insertion_point(field_get:UFinished.truckid)
  return truckid_;
}
inline void UFinished::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UFinished.truckid)
}

// required int32 x = 2;
inline bool UFinished::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UFinished::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UFinished::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UFinished::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 UFinished::x() const {
  // @@protoc_insertion_point(field_get:UFinished.x)
  return x_;
}
inline void UFinished::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:UFinished.x)
}

// required int32 y = 3;
inline bool UFinished::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UFinished::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UFinished::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UFinished::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 UFinished::y() const {
  // @@protoc_insertion_point(field_get:UFinished.y)
  return y_;
}
inline void UFinished::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:UFinished.y)
}

// -------------------------------------------------------------------

// UDeliveryMade

// required int32 truckid = 1;
inline bool UDeliveryMade::has_truckid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UDeliveryMade::set_has_truckid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UDeliveryMade::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UDeliveryMade::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UDeliveryMade::truckid() const {
  // @@protoc_insertion_point(field_get:UDeliveryMade.truckid)
  return truckid_;
}
inline void UDeliveryMade::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UDeliveryMade.truckid)
}

// required int64 packageid = 2;
inline bool UDeliveryMade::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UDeliveryMade::set_has_packageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UDeliveryMade::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UDeliveryMade::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 UDeliveryMade::packageid() const {
  // @@protoc_insertion_point(field_get:UDeliveryMade.packageid)
  return packageid_;
}
inline void UDeliveryMade::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:UDeliveryMade.packageid)
}

// -------------------------------------------------------------------

// UDeliveryLocation

// required int64 packageid = 1;
inline bool UDeliveryLocation::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UDeliveryLocation::set_has_packageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UDeliveryLocation::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UDeliveryLocation::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 UDeliveryLocation::packageid() const {
  // @@protoc_insertion_point(field_get:UDeliveryLocation.packageid)
  return packageid_;
}
inline void UDeliveryLocation::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:UDeliveryLocation.packageid)
}

// required int32 x = 2;
inline bool UDeliveryLocation::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UDeliveryLocation::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UDeliveryLocation::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UDeliveryLocation::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 UDeliveryLocation::x() const {
  // @@protoc_insertion_point(field_get:UDeliveryLocation.x)
  return x_;
}
inline void UDeliveryLocation::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:UDeliveryLocation.x)
}

// required int32 y = 3;
inline bool UDeliveryLocation::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UDeliveryLocation::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UDeliveryLocation::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UDeliveryLocation::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 UDeliveryLocation::y() const {
  // @@protoc_insertion_point(field_get:UDeliveryLocation.y)
  return y_;
}
inline void UDeliveryLocation::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:UDeliveryLocation.y)
}

// -------------------------------------------------------------------

// UGoDeliver

// required int32 truckid = 1;
inline bool UGoDeliver::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UGoDeliver::set_has_truckid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UGoDeliver::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UGoDeliver::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 UGoDeliver::truckid() const {
  // @@protoc_insertion_point(field_get:UGoDeliver.truckid)
  return truckid_;
}
inline void UGoDeliver::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UGoDeliver.truckid)
}

// repeated .UDeliveryLocation packages = 2;
inline int UGoDeliver::packages_size() const {
  return packages_.size();
}
inline void UGoDeliver::clear_packages() {
  packages_.Clear();
}
inline const ::UDeliveryLocation& UGoDeliver::packages(int index) const {
  // @@protoc_insertion_point(field_get:UGoDeliver.packages)
  return packages_.Get(index);
}
inline ::UDeliveryLocation* UGoDeliver::mutable_packages(int index) {
  // @@protoc_insertion_point(field_mutable:UGoDeliver.packages)
  return packages_.Mutable(index);
}
inline ::UDeliveryLocation* UGoDeliver::add_packages() {
  // @@protoc_insertion_point(field_add:UGoDeliver.packages)
  return packages_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UDeliveryLocation >*
UGoDeliver::mutable_packages() {
  // @@protoc_insertion_point(field_mutable_list:UGoDeliver.packages)
  return &packages_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UDeliveryLocation >&
UGoDeliver::packages() const {
  // @@protoc_insertion_point(field_list:UGoDeliver.packages)
  return packages_;
}

// -------------------------------------------------------------------

// UCommands

// repeated .UGoDeliver deliveries = 1;
inline int UCommands::deliveries_size() const {
  return deliveries_.size();
}
inline void UCommands::clear_deliveries() {
  deliveries_.Clear();
}
inline const ::UGoDeliver& UCommands::deliveries(int index) const {
  // @@protoc_insertion_point(field_get:UCommands.deliveries)
  return deliveries_.Get(index);
}
inline ::UGoDeliver* UCommands::mutable_deliveries(int index) {
  // @@protoc_insertion_point(field_mutable:UCommands.deliveries)
  return deliveries_.Mutable(index);
}
inline ::UGoDeliver* UCommands::add_deliveries() {
  // @@protoc_insertion_point(field_add:UCommands.deliveries)
  return deliveries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UGoDeliver >*
UCommands::mutable_deliveries() {
  // @@protoc_insertion_point(field_mutable_list:UCommands.deliveries)
  return &deliveries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UGoDeliver >&
UCommands::deliveries() const {
  // @@protoc_insertion_point(field_list:UCommands.deliveries)
  return deliveries_;
}

// repeated .UGoPickup pickups = 2;
inline int UCommands::pickups_size() const {
  return pickups_.size();
}
inline void UCommands::clear_pickups() {
  pickups_.Clear();
}
inline const ::UGoPickup& UCommands::pickups(int index) const {
  // @@protoc_insertion_point(field_get:UCommands.pickups)
  return pickups_.Get(index);
}
inline ::UGoPickup* UCommands::mutable_pickups(int index) {
  // @@protoc_insertion_point(field_mutable:UCommands.pickups)
  return pickups_.Mutable(index);
}
inline ::UGoPickup* UCommands::add_pickups() {
  // @@protoc_insertion_point(field_add:UCommands.pickups)
  return pickups_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UGoPickup >*
UCommands::mutable_pickups() {
  // @@protoc_insertion_point(field_mutable_list:UCommands.pickups)
  return &pickups_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UGoPickup >&
UCommands::pickups() const {
  // @@protoc_insertion_point(field_list:UCommands.pickups)
  return pickups_;
}

// optional uint32 simspeed = 3;
inline bool UCommands::has_simspeed() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UCommands::set_has_simspeed() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UCommands::clear_has_simspeed() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UCommands::clear_simspeed() {
  simspeed_ = 0u;
  clear_has_simspeed();
}
inline ::google::protobuf::uint32 UCommands::simspeed() const {
  // @@protoc_insertion_point(field_get:UCommands.simspeed)
  return simspeed_;
}
inline void UCommands::set_simspeed(::google::protobuf::uint32 value) {
  set_has_simspeed();
  simspeed_ = value;
  // @@protoc_insertion_point(field_set:UCommands.simspeed)
}

// optional bool disconnect = 4;
inline bool UCommands::has_disconnect() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UCommands::set_has_disconnect() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UCommands::clear_has_disconnect() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UCommands::clear_disconnect() {
  disconnect_ = false;
  clear_has_disconnect();
}
inline bool UCommands::disconnect() const {
  // @@protoc_insertion_point(field_get:UCommands.disconnect)
  return disconnect_;
}
inline void UCommands::set_disconnect(bool value) {
  set_has_disconnect();
  disconnect_ = value;
  // @@protoc_insertion_point(field_set:UCommands.disconnect)
}

// -------------------------------------------------------------------

// UResponses

// repeated .UFinished completions = 1;
inline int UResponses::completions_size() const {
  return completions_.size();
}
inline void UResponses::clear_completions() {
  completions_.Clear();
}
inline const ::UFinished& UResponses::completions(int index) const {
  // @@protoc_insertion_point(field_get:UResponses.completions)
  return completions_.Get(index);
}
inline ::UFinished* UResponses::mutable_completions(int index) {
  // @@protoc_insertion_point(field_mutable:UResponses.completions)
  return completions_.Mutable(index);
}
inline ::UFinished* UResponses::add_completions() {
  // @@protoc_insertion_point(field_add:UResponses.completions)
  return completions_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UFinished >*
UResponses::mutable_completions() {
  // @@protoc_insertion_point(field_mutable_list:UResponses.completions)
  return &completions_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UFinished >&
UResponses::completions() const {
  // @@protoc_insertion_point(field_list:UResponses.completions)
  return completions_;
}

// repeated .UDeliveryMade delivered = 2;
inline int UResponses::delivered_size() const {
  return delivered_.size();
}
inline void UResponses::clear_delivered() {
  delivered_.Clear();
}
inline const ::UDeliveryMade& UResponses::delivered(int index) const {
  // @@protoc_insertion_point(field_get:UResponses.delivered)
  return delivered_.Get(index);
}
inline ::UDeliveryMade* UResponses::mutable_delivered(int index) {
  // @@protoc_insertion_point(field_mutable:UResponses.delivered)
  return delivered_.Mutable(index);
}
inline ::UDeliveryMade* UResponses::add_delivered() {
  // @@protoc_insertion_point(field_add:UResponses.delivered)
  return delivered_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::UDeliveryMade >*
UResponses::mutable_delivered() {
  // @@protoc_insertion_point(field_mutable_list:UResponses.delivered)
  return &delivered_;
}
inline const ::google::protobuf::RepeatedPtrField< ::UDeliveryMade >&
UResponses::delivered() const {
  // @@protoc_insertion_point(field_list:UResponses.delivered)
  return delivered_;
}

// optional string error = 3;
inline bool UResponses::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UResponses::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UResponses::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UResponses::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& UResponses::error() const {
  // @@protoc_insertion_point(field_get:UResponses.error)
  return error_.GetNoArena();
}
inline void UResponses::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UResponses.error)
}
#if LANG_CXX11
inline void UResponses::set_error(::std::string&& value) {
  set_has_error();
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UResponses.error)
}
#endif
inline void UResponses::set_error(const char* value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UResponses.error)
}
inline void UResponses::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UResponses.error)
}
inline ::std::string* UResponses::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:UResponses.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UResponses::release_error() {
  // @@protoc_insertion_point(field_release:UResponses.error)
  clear_has_error();
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UResponses::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:UResponses.error)
}

// optional bool finished = 4;
inline bool UResponses::has_finished() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UResponses::set_has_finished() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UResponses::clear_has_finished() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UResponses::clear_finished() {
  finished_ = false;
  clear_has_finished();
}
inline bool UResponses::finished() const {
  // @@protoc_insertion_point(field_get:UResponses.finished)
  return finished_;
}
inline void UResponses::set_finished(bool value) {
  set_has_finished();
  finished_ = value;
  // @@protoc_insertion_point(field_set:UResponses.finished)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ups_2eproto__INCLUDED
